{{- if .Values.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openai.apiKeySecret.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.openai.apiKeySecret.key }}: {{ .Values.openai.apiKey }}
{{- else }}
{{- fail "OpenAI API Key must be provided. Set .Values.openai.apiKey in your values file or use --set openai.apiKey=your-api-key" }}
{{- end }}